WebAplication_ProximaGen/Models/AsignarPermisos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAplication_ProximaGen.Models
{
    public class AsignarPermisos
    {
        [Required(ErrorMessage = "El id es obligatorio")]
        public int idRol { get; set; }

        [Required(ErrorMessage = "El id es obligatorio")]
        public int idPermiso { get; set; }

        [Required(ErrorMessage = "El permiso es obligatorio")]
        public string permiso { get; set; }

        [Required(ErrorMessage = "El rol es obligatorio")]
        public string rol { get; set; }
    }
}

WebAplication_ProximaGen/Models/Contactos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAplication_ProximaGen.Models
{
    public class Contactos
    {
        [Required(ErrorMessage = "El id es obligatorio")]
        public int idContacto { get; set; }

        [Required(ErrorMessage = "La descripción de contacto es obligatorio")]
        public string descripcionContacto { get; set; }

        [Required(ErrorMessage = "El id tipo contacto es obligatorio")]
        public int TipoContactos_idTipoContacto { get; set; }

        [Required(ErrorMessage = "El id persona es obligatorio")]
        public int Personas_idPersona { get; set; }
    }
}

WebAplication_ProximaGen/Models/Generos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAplication_ProximaGen.Models
{
    public class Generos
    {
        [Required(ErrorMessage = "El id género es obligatorio")]
        public int idGenero { get; set; }

        [Required(ErrorMessage = "La descripción del género es obligatoria")]
        public string genero { get; set; }
    }
}

WebAplication_ProximaGen/Models/Permissions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAplication_ProximaGen.Models
{
    public class Permissions
    {
        [Required(ErrorMessage = "El id es obligatorio")]
        public int idPermiso { get; set; }

        [Required(ErrorMessage = "La descripción de permiso es obligatorio")]
        public string permiso { get; set; }
    }
}

WebAplication_ProximaGen/Models/Roles.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAplication_ProximaGen.Models
{
    public class Roles
    {
        [Required(ErrorMessage = "El id rol es obligatorio")]
        public int idRol { get; set; }

        [Required(ErrorMessage = "La descripción del rol es obligatorio")]
        public string descripcionRol { get; set; }
    }
}

WebAplication_ProximaGen/Models/Status.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAplication_ProximaGen.Models
{
    public class Status
    {
        [Required(ErrorMessage = "El id es obligatorio")]
        public int idEstado { get; set; }

        [StringLength(45)]
        [Required(ErrorMessage = "La descripción es obligatoria")]
        public string descripcionEstado { get; set; }
    }
}

WebAplication_ProximaGen/Models/Tarjetas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAplication_ProximaGen.Models
{
    public class Tarjetas
    {
        [Required(ErrorMessage = "El id es obligatorio")]
        public int idTarjeta { get; set; }

        [Required(ErrorMessage = "El número de tarjeta es obligatorio")]
        [RegularExpression("^[0-9]{16}$", ErrorMessage = "El número de tarjeta debe tener exactamente 16 dígitos y ser numérico")]
        public string numeroTarjeta { get; set; }

        [Required(ErrorMessage = "El mes de expiración es obligatorio")]
        public int expiracionMes { get; set; }

        [Required(ErrorMessage = "El año de expiración es obligatorio")]
        public int expiracionAnno { get; set; }

        [Required(ErrorMessage = "El cvv de expiración es obligatorio")]
        [StringLength(3, MinimumLength = 3, ErrorMessage = "El CVV debe tener exactamente 3 números")]
        public string cvv { get; set; }

        [Required(ErrorMessage = "El id de la persona es obligatorio")]
        public int Personas_idPersona { get; set; }

        [Required(ErrorMessage = "El id estado es obligatorio")]
        public int Estados_idEstado { get; set; }

    }
    
}

WebAplication_ProximaGen/Models/TipoContactos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAplication_ProximaGen.Models
{
    public class TipoContactos
    {
        [Required(ErrorMessage = "El id tipo contacto es obligatorio")]
        public int idTipoContacto { get; set; }

        [Required(ErrorMessage = "La descripción es obligatoria")]
        public string descripcionTipoContacto { get; set; }

    }
}

WebAplication_ProximaGen/Controllers/MaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAplication_ProximaGen.Models;
using WebAplication_ProximaGen.WS_Client;

namespace WebAplication_ProximaGen.Controllers
{
    public class MaintenanceController : Controller
    {
        // Instancia del Web Service
        WS_ProximaGenSoapClient wsClient = new WS_ProximaGenSoapClient();

        public ActionResult Person()
        {
            try
            {
                DataSet dataSet = new DataSet();

                List<Contactos> listacontactos = new List<Contactos>();
                dataSet = wsClient.LeerTipoContactos(0,100);
                foreach (DataRow dr in dataSet.Tables[0].Rows)
                {
                    var Contactos = new Contactos
                    {
                        TipoContactos_idTipoContacto = int.Parse(dr["idTipoContacto"].ToString()),
                        descripcionContacto = dr["descripcionTipoContacto"].ToString()
                    };
                    listacontactos.Add(Contactos);
                }

                TempData["listaTipoContacto"] = listacontactos;

                return View();
            }
            catch (Exception)
            {

                return View();
            }
        }

        public ActionResult Status()
        {
            try
            {
                var estados = LeerEstados(0, 100);
                TempData["Estados"] = estados;
                return View();
            }
            catch (Exception ex)
            {
                return View("ErrorView");
            }
        }

        public List<Status> LeerEstados(int inicio, int final)
        {
            try
            {
                DataSet dsEstado = new DataSet();
                dsEstado = wsClient.LeerEstados(inicio, final);

                // Convertir los datos a una lista de objetos Status
                var estados = new List<Status>();
                foreach (DataRow dr in dsEstado.Tables[0].Rows)
                {
                    var estado = new Status
                    {
                        idEstado = int.Parse(dr["idEstado"].ToString()),
                        descripcionEstado = dr["descripcionEstado"].ToString()
                    };
                    estados.Add(estado);
                }

                // Puedes almacenar la lista de estados en TempData para que esté disponible en la vista

                return estados;
            }
            catch (Exception)
            {

                return null;
            }

        }

        public ActionResult Permissions()
        {
            try
            {
                var permisos = LeerPermisos(0, 100);
                TempData["Permisos"] = permisos;
                return View();
            }
            catch (Exception ex)
            {
                // Manejo de errores (puedes registrar el error o redirigir a una página de error)
                // Por ejemplo, puedes registrar el error en un archivo de registro:
                // Log.Error(ex);
                return View("ErrorView"); // Puedes crear una vista de error personalizada
            }
        }

        public List<Permissions> LeerPermisos(int inicio, int final)
        {
            try
            {
                DataSet dsPermiso = new DataSet();
                dsPermiso = wsClient.Leer_Permisos(inicio, final);

                // Convertir los datos a una lista de objetos Permissions
                var permisos = new List<Permissions>();
                foreach (DataRow dr in dsPermiso.Tables[0].Rows)
                {
                    var permiso = new Permissions
                    {
                        idPermiso = int.Parse(dr["idPermiso"].ToString()),
                        permiso = dr["permiso"].ToString()
                    };
                    permisos.Add(permiso);
                }

                // Puedes almacenar la lista de permisos en TempData para que esté disponible en la vista

                return permisos;
            }
            catch (Exception)
            {

                return null;
            }

        }

        public ActionResult Roles()
        {
            try
            {
                var roles = LeerRoles(0, 100);
                TempData["Roles"] = roles;
                return View();
            }
            catch (Exception ex)
            {
                // Manejo de errores (puedes registrar el error o redirigir a una página de error)
                // Por ejemplo, puedes registrar el error en un archivo de registro:
                // Log.Error(ex);
                return View("ErrorView"); // Puedes crear una vista de error personalizada
            }
        }

        public List<Roles> LeerRoles(int inicio, int final)
        {
            try
            {
                DataSet dsRol = new DataSet();
                dsRol = wsClient.LeerRoles(inicio, final);

                // Convertir los datos a una lista de objetos Roles
                var roles = new List<Roles>();
                foreach (DataRow dr in dsRol.Tables[0].Rows)
                {
                    var rol = new Roles
                    {
                        idRol = int.Parse(dr["idRol"].ToString()),
                        descripcionRol = dr["descripcionRol"].ToString()
                    };
                    roles.Add(rol);
                }

                // Puedes almacenar la lista de roles en TempData para que esté disponible en la vista

                return roles;
            }
            catch (Exception)
            {

                return null;
            }

        }

        public ActionResult Generos()
        {
            try
            {
                var generos = LeerGeneros(0, 100);
                TempData["Generos"] = generos;
                return View();
            }
            catch (Exception ex)
            {
                // Manejo de errores (puedes registrar el error o redirigir a una página de error)
                // Por ejemplo, puedes registrar el error en un archivo de registro:
                // Log.Error(ex);
                return View("ErrorView"); // Puedes crear una vista de error personalizada
            }
        }

        public List<Generos> LeerGeneros(int inicio, int final)
        {
            try
            {
                DataSet dsGenero = new DataSet();
                dsGenero = wsClient.LeerGenero(inicio, final);

                // Convertir los datos a una lista de objetos Genero
                var generos = new List<Generos>();
                foreach (DataRow dr in dsGenero.Tables[0].Rows)
                {
                    var genero = new Generos
                    {
                        idGenero = int.Parse(dr["idGenero"].ToString()),
                        genero = dr["genero"].ToString()
                    };
                    generos.Add(genero);
                }

                // Puedes almacenar la lista de generos en TempData para que esté disponible en la vista

                return generos;
            }
            catch (Exception)
            {

                return null;
            }

        }

        public ActionResult Contactos()
        {
            try
            {
                var contactos = LeerContactos(0); //inicio,fin REVISAR SI DEBE QUEDAR CON PARAMETRO**
                TempData["Contactos"] = contactos;
                return View();
            }
            catch (Exception ex)
            {
                // Manejo de errores (puedes registrar el error o redirigir a una página de error)
                // Por ejemplo, puedes registrar el error en un archivo de registro:
                // Log.Error(ex);
                return View("ErrorView"); // Puedes crear una vista de error personalizada
            }
        }

        public List<Contactos> LeerContactos(int idPersona)
        {
            try
            {
                DataSet dsContactos = new DataSet();
                dsContactos = wsClient.Leer_Contactos(idPersona);

                // Convertir los datos a una lista de objetos Contactos
                var contactos = new List<Contactos>();
                foreach (DataRow dr in dsContactos.Tables[0].Rows)
                {
                    var contacto = new Contactos
                    {
                        idContacto = int.Parse(dr["idContacto"].ToString()),
                        descripcionContacto = dr["descripcionContacto"].ToString(),
                        TipoContactos_idTipoContacto = int.Parse(dr["TipoContactos_idTipoContacto"].ToString()),
                        Personas_idPersona = int.Parse(dr["Personas_idPersona"].ToString())
                    };
                    contactos.Add(contacto);
                }

                // Puedes almacenar la lista de contactos en TempData para que esté disponible en la vista

                return contactos;
            }
            catch (Exception)
            {

                return null;
            }

        }

        public ActionResult TipoContactos()
        {
            try
            {
                var tipocontactos = LeerTipoContacto(0, 100);
                TempData["TipoContactos"] = tipocontactos;
                return View();
            }
            catch (Exception ex)
            {
                // Manejo de errores (puedes registrar el error o redirigir a una página de error)
                // Por ejemplo, puedes registrar el error en un archivo de registro:
                // Log.Error(ex);
                return View("ErrorView"); // Puedes crear una vista de error personalizada
            }
        }

        public List<TipoContactos> LeerTipoContacto(int inicio, int final)
        {
            try
            {
                DataSet dsTipoContactos = new DataSet();

WebAplication_ProximaGen/Views/Maintenance/AsignarPermiso.cshtml
@{
    ViewBag.Title = "Asignar Permiso";
}

@using WebAplication_ProximaGen.Logica

@model WebAplication_ProximaGen.Models.AsignarPermisos

<section class="pc-container">
    <div class="pcoded-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Registros</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html">Administracion</a></li>
                            <li class="breadcrumb-item"><a href="#!">Mantenimiento</a></li>
                            <li class="breadcrumb-item">Asignar Permisos</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Asignar permisos por roles</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="mt-5">Ecoge el permiso</h5>
                        <hr>
                        @using (Html.BeginForm("CreateAsignarPermiso", "Maintenance", FormMethod.Post))
                        {
                            <form action="~/Maintenance/CreateAsignarPermiso" method="post">
                                <div class="row">
                                    
                                    <div class="form-group col-md-6">
                                        @Html.LabelFor(model => model.idPermiso, "Permiso", new { @class = "form-label" })
                                        @if (TempData["listaPermisos"] != null)
                                        {
                                            <select name="idPermiso" id="idPermiso" class="form-control">
                                                @foreach (var permiso in TempData["listaPermisos"] as List<WebAplication_ProximaGen.Models.Permissions>)
                                                {
                                                    <option class="form-control" value="@permiso.idPermiso">@permiso.permiso</option>
                                                }
                                            </select>
                                        }
                                    </div>
                                    <div class="form-group col-md-6">
                                        @Html.LabelFor(model => model.idRol, "Rol", new { @class = "form-label" })
                                        @if (TempData["listaRoles"] != null)
                                        {
                                            <select name="idRol" id="idRol" class="form-control">
                                                @foreach (var rol in TempData["listaRoles"] as List<WebAplication_ProximaGen.Models.Roles>)
                                                {
                                                    <option class="form-control" value="@rol.idRol">@rol.descripcionRol</option>
                                                }
                                            </select>
                                        }
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary mx-auto">Asignar Rol</button>
                                </div>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Listado de permisos por rol</h5>
                    <span class="d-block m-t-5">Este <code>lista</code> muestra los permisos asociados al rol</span>
                </div>
                <div class="card-body table-border-style">
                    @*<br>*@
                    @using (Html.BeginForm("LeerPermisosXRolQuery", "Maintenance", FormMethod.Post))
                    {
                        <div class="form-group">
                            @Html.LabelFor(model => model.idRol, "Rol", new { @class = "form-label" })
                            @if (TempData["listaRoles"] != null)
                            {
                                <select name="idRol" id="idRol" class="form-control">
                                    @foreach (var rol in TempData["listaRoles"] as List<WebAplication_ProximaGen.Models.Roles>)
                                    {
                                        <option class="form-control" value="@rol.idRol">@rol.descripcionRol</option>
                                    }
                                </select>
                            }
                            <br>
                            <input type="submit" value="Seleccionar" class="btn btn-primary" />
                            <br>
                        </div>
                    }



                    <div class="table-responsive">
                        <table id="tableTarjeta" class="table">
                            <thead>
                                <tr>
                                    <th>Id Permiso</th>
                                    <th>Permiso</th>
                                    <th>Id Rol</th>
                                    <th>Rol</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (TempData["permisosXRoles"] != null)
                                {
                                    foreach (var permisosXRol in TempData["permisosXRoles"] as List<WebAplication_ProximaGen.Models.AsignarPermisos>)
                                    {
                                        <tr>
                                            <td>@permisosXRol.idPermiso</td>
                                            <td>@permisosXRol.permiso</td>
                                            <td>@permisosXRol.idRol</td>
                                            <td>@permisosXRol.rol</td>
                                            <td>
                                                <a href="#" class="edit-icon" data-id="@permisosXRol.idPermiso" onclick="AbrirModal('@permisosXRol.idPermiso', '@permisosXRol.idRol');"><i class="fas fa-pen"></i></a>
                                                <a href="#" class="delete-icon" data-id="@permisosXRol.idPermiso" onclick="EliminarDato(@permisosXRol.idPermiso);"><i class="fas fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>



                    <!-- Agrega los botones de exportación aquí -->


                </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal para editar datos -->
<div class="modal fade" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editarModalLabel">Editar Datos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("UpdateAsignarPermiso", "Maintenance", FormMethod.Post))
            {
                <form>
                    <div class="modal-body">

                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.idPermiso, "Permiso", new { @class = "form-label" })
                            @if (TempData["listaPermisos"] != null)
                            {
                                <select name="idSelectRol" id="idSelectRol" class="form-control">
                                    @foreach (var persona in TempData["listaPermisos"] as List<WebAplication_ProximaGen.Models.Permissions>)
                                    {
                                        <option class="form-control" value="@persona.idPermiso">@persona.permiso</option>
                                    }
                                </select>
                            }
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.idRol, "Rol", new { @class = "form-label" })
                            @if (TempData["listaRoles"] != null)
                            {
                                <select name="idSelectRol" id="idSelectPermiso" class="form-control">
                                    @foreach (var estado in TempData["listaRoles"] as List<WebAplication_ProximaGen.Models.Roles>)
                                    {
                                        <option class="form-control" value="@estado.idRol">@estado.descripcionRol</option>
                                    }
                                </select>
                            }
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                    </div>
                </form>
            }
        </div>
    </div>
</div>


<script>


    function AbrirModal(idGenero, genero) {
        const idGeneroInput = document.getElementById("idSelectRol").value;
        const descripcionGeneroInput = document.getElementById("idSelectPermiso").value;

        idGeneroInput.value = idGenero;
        descripcionGeneroInput.value = genero;

        const editarModal = new bootstrap.Modal(document.getElementById("editarModal"));
        editarModal.show();
    }




    function EliminarDato(idGenero) {

        var controller = "Maintenance";
        var action = "DeleteGenero";
        var successMessage = "Se eliminó el género con éxito";
        var errorMessage = "No se ha eliminado, hubo un error de comunicación";
        var dataString = "idGenero";

        EliminarDatosAjax(idGenero, controller, action, successMessage, errorMessage, dataString);
    }

</script>

@if (TempData["responseCode"] != null)
{
    if (TempData["responseCode"] == null)
    {
        <script>
            CreateAlert('Fallo del sistema', 'error', 'No ha devuelto una respuesta, comuniquese con IT');
        </script>
    }

    if (TempData["responseCode"].ToString().Contains(Constantes.responsesCode[0].ToString()))
    {
        <script>
            var decodedResponse = @Html.Raw(Json.Encode(TempData["response"]));
            CreateAlert('Creación Exitosa', 'success', decodedResponse);
        </script>
    }

    if (TempData["responseCode"].ToString().Contains(Constantes.responsesCode[1].ToString()))
    {
        <script>
            var decodedResponse = @Html.Raw(Json.Encode(TempData["response"]));
            CreateAlert('Creación Denegada', 'error', decodedResponse);
        </script>
    }

    TempData["responseCode"] = null;
}